# Generated by Django 4.2.1 on 2023-06-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chat_participants',
        ),
    ]
