# Generated by Django 4.2.1 on 2023-06-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
